name: My Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send JSON manifest to Boomi
        run: |
          BOOMI_REQUEST=$(curl -X POST https://c01-sg.integrate-test.boomi.com/ws/simple/getCICD \
          -u ${{ secrets.BASICAUTH }} \
          -H "Content-Type: application/json" \
          -d '{
            "ProcessName": "${{ github.event.repository.name }}",
            "EnvironmentId": [ "${{ secrets.QA_ENVID }}" ]
          }')

          echo "Boomi Request: $BOOMI_REQUEST"
